import {useEffect,useMemo,useState} from 'react'
import {getCandidates,saveProgramming} from '../api'
const CONDITIONS=['','OPERANDO','EQUIPO DETENIDO','LINEA DETENIDA','AREA/PLANTA DETENIDA','SIN CLASIFICAR']
function exportCsv(rows,specialty){if(!rows.length)return;const headers=['Orden','Área','Línea','Activo','Descripción','Grupo','Plan','Criticidad','Condición','Personas','Tiempo min','HH','Origen'];const data=rows.map(x=>[x.numero_orden||'',x.area_nombre||'',x.linea_nombre||'',x.activo_codigo,x.activo_descripcion,x.grupo_plan,x.plan_trabajo,x.criticidad||'',x.condicion,x.personas_usar,x.tiempo_planeado_min,x.hh_pmp,x.origen]);const csv=[headers,...data].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`programacion_${specialty}.csv`;a.click();URL.revokeObjectURL(url)}
export default function SpecialtyPlanner({specialty,capacity,week}){
 const [candidates,setCandidates]=useState([]),[selected,setSelected]=useState([]),[area,setArea]=useState(''),[criticality,setCriticality]=useState(''),[condition,setCondition]=useState(''),[planText,setPlanText]=useState(''),[chosenPlan,setChosenPlan]=useState(''),[equipmentId,setEquipmentId]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{const timer=setTimeout(async()=>{try{const rows=await getCandidates({specialty,area:area||undefined,criticality:criticality||undefined,condition:condition||undefined,plan_search:planText||undefined,limit:1000});setCandidates(rows.filter(x=>!selected.some(s=>s.pmp_id===x.pmp_id)))}catch(e){setMessage(e.message)}},180);return()=>clearTimeout(timer)},[specialty,area,criticality,condition,planText,selected])
 const planOptions=useMemo(()=>[...new Set(candidates.map(x=>x.plan_trabajo))].sort(),[candidates]);const areaOptions=useMemo(()=>[...new Set(candidates.map(x=>x.area_nombre).filter(Boolean))].sort(),[candidates]);const equipment=useMemo(()=>candidates.filter(x=>x.plan_trabajo===chosenPlan),[candidates,chosenPlan]);const target=Number(capacity?.target||0);const used=selected.reduce((s,x)=>s+Number(x.hh_pmp||0),0)
 function choosePlan(plan){setChosenPlan(plan);setPlanText(plan);setEquipmentId('')}
 function add(){const item=candidates.find(x=>String(x.pmp_id)===equipmentId);if(!item)return setMessage('Selecciona un equipo');const next=used+Number(item.hh_pmp||0);if(target<=0)return setMessage('Primero calcula la disponibilidad');if(next>target+.0001)return setMessage(`No se puede agregar: ${next.toFixed(1)} HH supera la meta ${target.toFixed(1)} HH`);if(item.condicion==='SIN CLASIFICAR')return setMessage('Este plan está SIN CLASIFICAR');setSelected(p=>[...p,item]);setEquipmentId('');setChosenPlan('');setPlanText('');setMessage('Actividad agregada')}
 async function save(){if(!week?.from||!week?.to)return setMessage('Selecciona y calcula la semana primero');if(!selected.length)return setMessage('No hay actividades');try{const r=await saveProgramming({date_from:week.from,date_to:week.to,specialty,pmp_ids:selected.map(x=>x.pmp_id)});setMessage(`Programación guardada · ${Number(r.hh_programmed).toFixed(1)} HH · versión ${r.version}`);setSelected([])}catch(e){setMessage(e.message)}}
 return <section className="planner"><div className="metrics"><div><span>Disponibles</span><b>{Number(capacity?.available||0).toFixed(1)} HH</b></div><div><span>Meta 80%</span><b>{target.toFixed(1)} HH</b></div><div><span>Seleccionadas</span><b>{used.toFixed(1)} HH</b></div><div><span>Restantes</span><b>{Math.max(0,target-used).toFixed(1)} HH</b></div></div>
 <div className="filters"><select value={area} onChange={e=>setArea(e.target.value)}><option value="">Todas las áreas</option>{areaOptions.map(x=><option key={x}>{x}</option>)}</select><select value={criticality} onChange={e=>setCriticality(e.target.value)}><option value="">Todas las criticidades</option><option>A</option><option>B</option><option>C</option></select><select value={condition} onChange={e=>setCondition(e.target.value)}>{CONDITIONS.map(x=><option key={x} value={x}>{x||'Todas las condiciones'}</option>)}</select><span className="origin-filter">Mes actual + Backlog</span></div>
 <div className="selector-row"><div className="plan-combo"><label>Actividad / Plan de Trabajo</label><input value={planText} onChange={e=>{setPlanText(e.target.value);setChosenPlan('')}} placeholder="Escribe para buscar..."/>{planText&&!chosenPlan&&<div className="suggestions">{planOptions.slice(0,80).map(p=><button key={p} onClick={()=>choosePlan(p)}>{p}</button>)}</div>}</div><label>Equipo / Activo<select value={equipmentId} onChange={e=>setEquipmentId(e.target.value)} disabled={!chosenPlan}><option value="">— Selecciona equipo —</option>{equipment.map(x=><option key={x.pmp_id} value={x.pmp_id}>{x.activo_codigo} — {x.activo_descripcion} — {Number(x.hh_pmp).toFixed(1)} HH</option>)}</select></label><button className="primary" onClick={add}>Agregar</button></div><div className="message">{message}</div>
 <div className="table-actions"><button onClick={()=>exportCsv(selected,specialty)}>Exportar programación</button><button className="primary" onClick={save}>Guardar programación</button></div><div className="table-wrap"><table><thead><tr><th>Quitar</th><th>Orden</th><th>Área</th><th>Línea</th><th>Activo</th><th>Plan</th><th>Crit.</th><th>Condición</th><th>HH</th><th>Origen</th></tr></thead><tbody>{!selected.length&&<tr><td colSpan="10" className="empty">Aún no has seleccionado PMP.</td></tr>}{selected.map(x=><tr key={x.pmp_id}><td><button onClick={()=>setSelected(p=>p.filter(i=>i.pmp_id!==x.pmp_id))}>Quitar</button></td><td>{x.numero_orden||'SIN ASIGNAR'}</td><td>{x.area_nombre}</td><td>{x.linea_nombre}</td><td>{x.activo_codigo} — {x.activo_descripcion}</td><td>{x.plan_trabajo}</td><td>{x.criticidad}</td><td>{x.condicion}</td><td>{Number(x.hh_pmp).toFixed(1)}</td><td>{x.origen}</td></tr>)}</tbody></table></div></section>
}
