import {useEffect,useMemo,useState} from 'react'
import {getV2WeekProgramming,saveV2WeekProgramming,downloadV2WeeklyReport} from '../api'
import {emptyFilters,matchesFilters,updateGroupFilters} from '../features/planning/weeklyProgrammingFilters'
import {toggleWeeklySelection} from '../features/planning/weeklyProgrammingSelection'
import Badge from '../shared/Badge'

const MONTHS=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre']
const SPEC_NAMES={MEC:'Mecánica',ELE:'Eléctrica',MET:'Metrología',SER:'Servicios'}
const SPECS=['MEC','ELE','MET','SER']

function number(value,fallback=0){const parsed=Number(value);return Number.isFinite(parsed)?parsed:fallback}
function fmt(value,decimals=1){return number(value).toLocaleString('es-CO',{minimumFractionDigits:decimals,maximumFractionDigits:decimals})}
function monthWeeks(year,month){const days=new Date(year,month,0).getDate();const weeks=[];for(let start=1;start<=days;start+=7){const end=Math.min(start+6,days);weeks.push({from:`${year}-${String(month).padStart(2,'0')}-${String(start).padStart(2,'0')}`,to:`${year}-${String(month).padStart(2,'0')}-${String(end).padStart(2,'0')}`,label:`${start}–${end} ${MONTHS[month-1]}`})}return weeks}

function ActivityGroup({kind,rows,dashboard,editing,filters,onFiltersChange,onToggle}){
  const config={operating:{kicker:'EQUIPO OPERANDO',title:'Actividades con equipo operando',description:'Trabajos que pueden ejecutarse sin detener el equipo.',tone:'ok'},stopped:{kicker:'PARADA REQUERIDA',title:'Actividades que requieren parada',description:'Trabajos que necesitan coordinación de detención.',tone:'stop'},backlog:{kicker:'BACKLOG',title:'Backlog de programaciones anteriores',description:'OT retiradas de una programación anterior que debes revisar primero.',tone:'backlog'}}[kind]
  const visible=matchesFilters(rows,filters)
  return <section className={'v2-activity-section '+kind} aria-label={config.title}>
    <div className="v2-activity-head"><div><span className="v2-kicker">{config.kicker}</span><h3>{config.title}</h3><p>{config.description}</p></div><Badge tone={config.tone}>{visible.length} disponibles</Badge></div>
    <div className="v2-group-filters" aria-label={`Filtros de ${config.title}`}><div className="v2-group-filter-title"><span>Filtros independientes</span><b>{config.kicker}</b></div><label><span>Area</span><select aria-label={`Área en ${config.title}`} value={filters.area} onChange={event=>onFiltersChange({area:event.target.value})}><option value="">Todas las áreas</option>{(dashboard?.areas||[]).map(area=><option key={area.codigo} value={area.codigo}>{area.codigo} · {area.nombre||area.codigo}</option>)}</select></label><label><span>Buscar</span><input aria-label={`Buscar en ${config.title}`} placeholder="OT, equipo o plan..." value={filters.search} onChange={event=>onFiltersChange({search:event.target.value})}/></label></div>
    <div className="v2-table-wrap v2-program-table"><table><thead><tr>{kind==='backlog'&&<th>Origen</th>}<th>OT</th><th>Área</th><th>Equipo</th><th>Plan de trabajo</th><th>Personas</th><th>Tiempo</th><th>H-H</th><th>Seleccionar</th></tr></thead><tbody>{visible.map(row=><tr key={row.orden_mantenimiento_id}>{kind==='backlog'&&<td><div className="v2-backlog-origin"><b>Movida</b><small>{row.semana_origen_inicio||'Semana anterior'} → {row.semana_origen_fin||''}</small></div></td>}<td><b>{row.numero_ot||'SIN ASIGNAR'}</b></td><td><Badge>{row.area_codigo||'—'}</Badge><small>{row.area_nombre||''}</small></td><td><b>{row.activo_codigo}</b><small>{row.activo_descripcion}</small></td><td><span className="v2-plan">{row.plan_trabajo}</span><small>{row.descripcion_grupo||''}</small></td><td><b>{row.numero_personas_efectivo}</b></td><td>{fmt(row.tiempo_min,0)} min</td><td><b>{fmt(row.hh,1)}</b></td><td><button type="button" className="v2-select" disabled={!editing} onClick={()=>onToggle(row)}>{editing?'Seleccionar':'Solo lectura'}</button></td></tr>)}{!visible.length&&<tr><td colSpan={kind==='backlog'?9:8} className="v2-empty">No hay actividades con estos filtros.</td></tr>}</tbody></table></div>
  </section>
}

function SelectionSummary({rows,editing,onToggle}){
  const operatingHH=rows.filter(row=>row.requiere_parada===false).reduce((sum,row)=>sum+number(row.hh),0)
  const stoppedHH=rows.filter(row=>row.requiere_parada===true).reduce((sum,row)=>sum+number(row.hh),0)
  const totalHH=operatingHH+stoppedHH
  return <section className={'v2-selected-section '+(!editing?'readonly':'')}><div className="v2-selected-head"><div><span className="v2-kicker">{editing?'PROGRAMACIÓN EN EDICIÓN':'PROGRAMACIÓN GUARDADA'}</span><h3>{editing?'Selección actual':'Programación actual de la semana'}</h3><p>{editing?'Revisa lo que ya agregaste antes de seguir buscando actividades.':'Consulta la última versión guardada.'}</p></div><div className="v2-selected-totals"><span><b>{rows.length}</b> actividades</span><span><b>{fmt(operatingHH,1)}</b> H-H operando</span><span><b>{fmt(stoppedHH,1)}</b> H-H detenido</span><span className="total"><b>{fmt(totalHH,1)}</b> H-H total</span></div></div><div className="v2-table-wrap v2-selected-table"><table><thead><tr><th>Condición</th><th>Origen</th><th>OT</th><th>Área</th><th>Equipo</th><th>Plan de trabajo</th><th>Personas</th><th>Tiempo</th><th>H-H</th>{editing&&<th>Acción</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.orden_mantenimiento_id}><td>{row.requiere_parada?<Badge tone="stop">Equipo detenido</Badge>:<Badge tone="ok">Equipo funcionando</Badge>}</td><td>{row.origen==='BACKLOG'||row.origen_backlog?<Badge tone="backlog">BACKLOG</Badge>:<Badge>PMP DEL MES</Badge>}</td><td><b>{row.numero_ot||'SIN ASIGNAR'}</b></td><td><Badge>{row.area_codigo||'—'}</Badge><small>{row.area_nombre||''}</small></td><td><b>{row.activo_codigo}</b><small>{row.activo_descripcion}</small></td><td><span className="v2-plan">{row.plan_trabajo}</span><small>{row.descripcion_grupo||''}</small></td><td><b>{row.numero_personas_efectivo}</b></td><td>{fmt(row.tiempo_min,0)} min</td><td><b>{fmt(row.hh,1)}</b></td>{editing&&<td><button type="button" className="v2-unselect" onClick={()=>onToggle(row)}>Quitar → Backlog</button></td>}</tr>)}{!rows.length&&<tr><td colSpan={editing?10:9} className="v2-empty">Todavía no has seleccionado actividades para esta semana.</td></tr>}</tbody></table></div></section>
}

export default function WeeklyProgramming({year,month,dashboard}){
  const weeks=useMemo(()=>monthWeeks(year,month),[year,month])
  const [weekIndex,setWeekIndex]=useState(0);const [specialty,setSpecialty]=useState('MEC');const [data,setData]=useState(null);const [selected,setSelected]=useState(new Set());const [filters,setFilters]=useState(emptyFilters);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [dirty,setDirty]=useState(false);const [programmingId,setProgrammingId]=useState(null);const [editing,setEditing]=useState(true)
  const week=weeks[Math.min(weekIndex,weeks.length-1)]||weeks[0]
  async function load(){if(!week)return;try{setLoading(true);setError('');const result=await getV2WeekProgramming(week.from,week.to,specialty);setData(result);setSelected(new Set((result.selected_ids||[]).map(Number)));setProgrammingId(result.programming?.id||null);setEditing(!result.programming);setDirty(false)}catch(cause){setError(cause.message)}finally{setLoading(false)}}
  useEffect(()=>{setWeekIndex(0)},[month]);useEffect(()=>{load()},[week?.from,week?.to,specialty])
  const allRows=useMemo(()=>[...(data?.operating||[]),...(data?.stopped||[]),...(data?.backlog||[])],[data])
  const rowMap=useMemo(()=>new Map(allRows.map(row=>[Number(row.orden_mantenimiento_id),row])),[allRows])
  const selectedRows=useMemo(()=>[...selected].map(id=>rowMap.get(Number(id))).filter(Boolean).sort((left,right)=>Number(left.requiere_parada)-Number(right.requiere_parada)||String(left.area_codigo||'').localeCompare(String(right.area_codigo||''))||String(left.numero_ot||'').localeCompare(String(right.numero_ot||''))),[selected,rowMap])
  const selectedHH=useMemo(()=>selectedRows.reduce((sum,row)=>sum+number(row.hh),0),[selectedRows])
  const target=number(data?.capacity?.target);const available=number(data?.capacity?.available);const effective=number(data?.capacity?.effective);const reserve=number(data?.capacity?.reserve);const initialMargin=number(data?.capacity?.initial_margin);const techniciansAvailable=number(data?.capacity?.technicians_available,data?.capacity?.technicians||0);const techniciansAssigned=number(data?.capacity?.technicians_assigned,data?.capacity?.technicians||0);const remaining=Math.max(0,target-selectedHH);const progress=target>0?Math.min(100,selectedHH/target*100):0
  function updateFilters(kind,patch){setFilters(current=>updateGroupFilters(current,kind,patch))}
  function toggle(row){if(!editing)return;const id=Number(row.orden_mantenimiento_id);setError('');setMessage('');setSelected(current=>{const result=toggleWeeklySelection({selected:current,id,row,rowMap,target});if(result.error){setError(`No se puede seleccionar esta actividad: llegarías a ${fmt(result.nextHH,1)} H-H y la meta máxima es ${fmt(target,1)} H-H.`);return current}if(result.changed)setDirty(true);return result.selected})}
  async function save(){if(!selected.size){setError('Selecciona al menos una orden para guardar la semana.');return}try{setSaving(true);setError('');setMessage('');const result=await saveV2WeekProgramming({date_from:week.from,date_to:week.to,specialty,order_ids:[...selected]});setProgrammingId(result.programming_id);setDirty(false);await load();setMessage(`Programación guardada: ${fmt(result.hh_programmed,1)} H-H de ${fmt(result.hh_target,1)} H-H objetivo.${result.moved_to_backlog?` ${result.moved_to_backlog} OT movida(s) a BACKLOG.`:''}`)}catch(cause){setError(cause.message)}finally{setSaving(false)}}
  async function report(format){if(!programmingId||dirty){setError('Guarda la programación antes de generar el reporte.');return}try{setError('');await downloadV2WeeklyReport(programmingId,format)}catch(cause){setError(cause.message)}}
  function cancelEdit(){load();setMessage('Cambios descartados. La programación vuelve a la última versión guardada.')}
  const groups=[{kind:'operating',rows:(data?.operating||[]).filter(row=>!selected.has(Number(row.orden_mantenimiento_id)))},{kind:'stopped',rows:(data?.stopped||[]).filter(row=>!selected.has(Number(row.orden_mantenimiento_id)))},{kind:'backlog',rows:(data?.backlog||[]).filter(row=>!selected.has(Number(row.orden_mantenimiento_id)))}]
  return <div className="v2-stack v2-weekly-programming">
    <section className="v2-panel v2-week-context"><div className="v2-section-head"><div><span className="v2-kicker">PROGRAMACIÓN SEMANAL</span><h3>Semana y especialidad de trabajo</h3><p>Selecciona el contexto antes de revisar capacidad, actividades y programación actual.</p></div><Badge>{loading?'Calculando...':`${techniciansAvailable} disponibles / ${techniciansAssigned} asignados`}</Badge></div><div className="v2-week-selector"><div className="v2-week-buttons">{weeks.map((item,index)=><button type="button" key={item.from} className={weekIndex===index?'active':''} onClick={()=>setWeekIndex(index)}><b>Semana {index+1}</b><span>{item.label}</span></button>)}</div><div className="v2-specialty-buttons">{SPECS.map(item=><button type="button" key={item} className={specialty===item?'active':''} onClick={()=>setSpecialty(item)}><b>{item}</b><span>{SPEC_NAMES[item]}</span></button>)}</div></div></section>
    {programmingId&&<section className="v2-program-review"><div><span className="v2-kicker">PROGRAMACIÓN EXISTENTE</span><h3>{editing?'Modificando programación guardada':'Programación disponible para consulta'}</h3><p>{editing?'Los cambios no afectan la programación hasta que los guardes.':'Puedes revisar o exportar esta versión; activa edición para modificarla.'}</p></div><div className="v2-program-review-actions">{!editing?<button type="button" className="v2-primary" onClick={()=>{setEditing(true);setMessage('Modo edición activado. Los cambios no afectan la programación hasta que presiones Guardar cambios.')}}>Modificar programación</button>:<button type="button" onClick={cancelEdit}>Cancelar cambios</button>}<button type="button" disabled={dirty} onClick={()=>report('xlsx')}>Exportar Excel</button><button type="button" disabled={dirty} onClick={()=>report('pdf')}>Exportar PDF</button></div></section>}
    <section className="v2-capacity-panel v2-capacity-summary"><div className="v2-capacity-cards"><div><span>H-H disponibles</span><b>{fmt(available,1)}</b><small>técnicos y turnos</small></div><div className="target"><span>Meta programable</span><b>{fmt(target,1)}</b><small>límite semanal</small></div><div className="selected"><span>H-H seleccionadas</span><b>{fmt(selectedHH,1)}</b><small>{selected.size} actividades</small></div><div className={remaining<=.01?'complete':'remaining'}><span>{remaining<=.01?'Meta alcanzada':'Faltan para meta'}</span><b>{fmt(remaining,1)}</b><small>H-H</small></div></div><div className="v2-capacity-details"><span>Capacidad efectiva <b>{fmt(effective,1)}</b> H-H</span><span>Margen inicial <b>{fmt(initialMargin,1)}</b> H-H</span><span>Reserva <b>{fmt(reserve,1)}</b> H-H</span></div><div className="v2-progress-block"><div className="v2-progress-copy"><span>Avance hacia la meta programable</span><b>{fmt(progress,1)}%</b></div><div className="v2-progress-track"><i style={{width:`${progress}%`}}/></div><div className="v2-progress-foot"><span>{fmt(selectedHH,1)} H-H programadas</span><span>Objetivo {fmt(target,1)} H-H</span></div></div>{available===0&&<div className="v2-warning">Esta especialidad no tiene disponibilidad cargada para esta semana. Revisa la programación de técnicos.</div>}</section>
    <SelectionSummary rows={selectedRows} editing={editing} onToggle={toggle}/>
    {(editing||!programmingId)&&<section className="v2-save-program v2-program-action-bar"><div className="v2-save-program-copy"><span className="v2-kicker">{programmingId?'GUARDAR MODIFICACIÓN':'CIERRE DE PROGRAMACIÓN'}</span><h3>{dirty?'Hay cambios sin guardar':programmingId?'Programación abierta para edición':'Guarda la selección de esta semana'}</h3><div className="v2-save-summary"><span><b>{fmt(selectedHH,1)}</b> H-H seleccionadas</span><span><b>{fmt(target,1)}</b> H-H meta</span><span><b>{fmt(remaining,1)}</b> H-H faltantes</span></div>{error&&<div className="v2-error v2-error-bottom">{error}</div>}{message&&<div className="v2-success v2-success-bottom">{message}</div>}</div><div className="v2-report-actions"><button type="button" className="v2-primary" disabled={saving||!selected.size||selectedHH>target+.001||(!dirty&&!!programmingId)} onClick={save}>{saving?'Guardando...':programmingId?'Guardar cambios':'Guardar programación'}</button>{programmingId&&<button type="button" onClick={cancelEdit}>Cancelar</button>}</div></section>}
    <section className="v2-panel v2-available-work"><div className="v2-program-toolbar"><div><span className="v2-kicker">ACTIVIDADES DISPONIBLES</span><h3>{editing?'Filtra cada grupo por separado':'Cartera de actividades · solo lectura'}</h3><p>Cada grupo conserva su propia búsqueda y área.</p></div></div>{groups.map(group=><ActivityGroup key={group.kind} {...group} dashboard={dashboard} editing={editing} filters={filters[group.kind]} onFiltersChange={patch=>updateFilters(group.kind,patch)} onToggle={toggle}/>)}</section>
  </div>
}
